export enum BusinessType {
  GROCERY = "GROCERY",
  MEDICAL = "MEDICAL",
  CLOTHING = "CLOTHING",
  FOOTWEAR = "FOOTWEAR",
  HARDWARE = "HARDWARE",
  ELECTRONICS = "ELECTRONICS",
  OTHER = "OTHER",
}
